name: Build & Tests (server)

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_test_run:
    name: Build and test
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - name: Use cached dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: "ubuntu-22.04-x86_64-unknown-linux-gnu"

      - name: Install Diesel CLI
        run: |
          apt-get update && install libpq-dev -y
          cargo install diesel_cli --no-default-features --features postgres

      - name: Build
        run: cargo build --all-targets

      - name: Test
        run: cargo test

  lint:
    name: Lint
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use cached dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: "ubuntu-22.04-x86_64-unknown-linux-gnu"

      - name: Install clippy and rustfmt
        run: |
          rustup component add clippy
          rustup component add rustfmt

      - name: Run clippy
        run: cargo clippy -- -Dwarnings

      - name: Run fmt
        run: cargo fmt --check
